/* 
 * test_factorial.h - structures and function declarations for unit tests
 * of factorial functions.
 * 
 * DO NOT EDIT THIS FILE.
 */ 
#ifndef _TEST_FACTORIAL_H
#define _TEST_FACTORIAL_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit.h"

/* known entry point to run all unit tests */
int run_munit_tests(int argc, char** argv);

MunitResult test_factorial(const MunitParameter params[], void* fixture);
MunitResult test_rfactorial(const MunitParameter params[], void* fixture);
MunitResult test_trfactorial(const MunitParameter params[], void* fixture);

static MunitTest tests[] = {
    { "/test_factorial", test_factorial, NULL, NULL, MUNIT_TEST_OPTION_NONE,
        NULL },
    { "/test_rfactorial", test_rfactorial, NULL, NULL, MUNIT_TEST_OPTION_NONE,
        NULL },
    { "/test_trfactorial", test_trfactorial, NULL, NULL, MUNIT_TEST_OPTION_NONE,
        NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_factorial", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif