/*
 * test_factorial.c
 * 
 * DO NOT EDIT THIS FILE
 * 
 * Unit tests of factorial functions declared in factorial.h.
 * 
 * This file contains the following test functions:
 *      test_factorial that can be called with a pointer to the 
 *      the factorial function to test
 */
 
#include <errno.h>
#include <stdio.h>
#include "factorial.h"
/* 
 * test_factorial.c - unit tests of factorial functions.
 * 
 * 
 * DO NOT EDIT THIS FILE.
 */
#include "test_factorial.h"

int run_munit_tests(int argc, char** argv) {
    /*
     * Each element of factorial_result is the expected result for the 
     * factorial of its index position, e.g
     * factorial(index) == factorial_result[index]
     */
    int factorial_result[] = {
        1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800, 39916800,
        479001600, -1
    };

    return munit_suite_main(&suite, factorial_result, argc, argv);
}

MunitResult generic_test_factorial(int (*factorial_f)(int), 
    int* expected_result) {
    errno = 0;
    assert_int(factorial_f(-1), ==, -1);
    assert_int(errno, ==, EINVAL);
    errno = 0;
    assert_int(factorial_f(-10), ==, -1);
    assert_int(errno, ==, EINVAL);
    errno = 0;
    
    /*
     * Each element of result is the expected result for the 
     * factorial of its index position, e.g
     * factorial(index) == result[i]
     */
    printf("\n    with input i: "); 
    for (int i = 0; expected_result[i] > -1; i++) {
        printf("%d ", i);
        assert_int(factorial_f(i), ==, expected_result[i]);
    }
    printf("\n");
    
    return MUNIT_OK;
}

MunitResult test_factorial(const MunitParameter params[], void* fixture) {
    printf("\n    testing factorial ...");
    return generic_test_factorial(factorial, fixture);
}

MunitResult test_rfactorial(const MunitParameter params[], void* fixture) {
    printf("\n    testing rfactorial ...");
    return generic_test_factorial(rfactorial, fixture);
}

MunitResult test_trfactorial(const MunitParameter params[], void* fixture) {
    printf("\n    testing trfactorial ...");
    int* expected_result = (int*) fixture;
    errno = 0;
    assert_int(trfactorial(-1, 1), ==, -1);
    assert_int(errno, ==, EINVAL);
    errno = 0;
    assert_int(trfactorial(-10, 1), ==, -1);
    assert_int(errno, ==, EINVAL);
    errno = 0;
    
    /*
     * Each element of factorial_result is the expected result for the 
     * factorial of its index position, e.g
     * factorial(index) == factorial_result[i]
     */    
    printf("\n    with input i: "); 
    for (int i = 0; expected_result[i] > -1; i++) {
        printf("%d ", i);
        assert_int(trfactorial(i, 1), ==, expected_result[i]);
    }
    printf("\n");
    
    return MUNIT_OK;
}

